version: '3.8' 

services:
  sqlite-php-server:
    container_name: php-server
    build: ../../
    ports:
      - "1337:1337"  
    volumes:
      - .:/home/sqlite-php-server 
    working_dir: /home/sqlite-php-server 
    environment: 
      - AIKIDO_BLOCKING=1
      - AIKIDO_DEBUG=1
      - AIKIDO_BLOCK=1
    command: php -S 0.0.0.0:1337
