name: Create images for building extension

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile.build-extension
      - .github/workflows/build-images/build-extension-images.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-build-extension

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php_version: ['7.2','7.3','7.4','8.0','8.1','8.2','8.3','8.4']

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive tags
        id: meta
        run: |
          V="${{ matrix.php_version }}"
          echo "tag_dev=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${V}" >> $GITHUB_OUTPUT

      - name: Build & Push (dev)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.build-extension
          target: dev
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            PHP_SRC_REF=PHP-${{ matrix.php_version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tag_dev }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache-${{ matrix.php_version }}
         