name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      php_version:
        description: 'PHP version to build against'
        required: true
        default: '8.0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf bison re2c libxml2-dev libssl-dev libcurl4-gnutls-dev

    - name: Get Aikido version
      run: |
        AIKIDO_VERSION=$(grep '# define PHP_AIKIDO_VERSION' include/php_aikido.h | awk -F'"' '{print $2}')
        echo $AIKIDO_VERSION
        echo "AIKIDO_VERSION=$AIKIDO_VERSION" >> $GITHUB_ENV

    - name: Clone PHP source
      run: |
        git clone https://github.com/php/php-src.git
        cd php-src
        git checkout PHP-${{ github.event.inputs.php_version }}

    - name: Build PHP
      run: |
        cd php-src
        ./buildconf
        ./configure --prefix=$HOME/php --with-config-file-path=$HOME/php
        make -j$(nproc)
        make install

    - name: Set PHP PATH
      run: echo "PATH=$HOME/php/bin:$PATH" >> $GITHUB_ENV

    - name: Run PHP
      run: php -v
 
    - name: Build Curl
      run: |
        cd php-src/ext/curl
        phpize
        ./configure
        make
        make install

    - name: Build Aikido
      run: |
        cd ${{ github.workspace }}
        rm -rf build
        mkdir build
        cd src/extension
        phpize
        cd ../lib
        go build -buildmode=c-archive -o ../../build/libaikido_go.a
        cd ../../build
        CXX=g++ CXXFLAGS="-fPIC -I../include" LDFLAGS="-L./ -laikido_go" ../src/extension/configure --with-php-config=$HOME/php/bin/php-config
        make
        make install

    - name: Test
      run: |
        cd ${{ github.workspace }}
        php src/extension/run-tests.php ./tests
        
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aikido-${{ env.AIKIDO_VERSION }}-php-${{ matrix.php_version }}
        path: ${{ github.workspace }}/build/modules/aikido.so
        if-no-files-found: error
