name: Build libs toolchain image

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Dockerfile.build-libs
      - .github/workflows/build-libs-image.yml

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_LIBS: aikidosec/firewall-php-build-libs
  VERSION: v1

jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .github/workflows/Dockerfile.build-libs
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LIBS }}:${{ env.VERSION }}-amd64
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LIBS }}:cache-${{ env.VERSION }}-amd64
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LIBS }}:cache-${{ env.VERSION }}-amd64,mode=max

  build-arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push (arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .github/workflows/Dockerfile.build-libs
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LIBS }}:${{ env.VERSION }}-arm64
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LIBS }}:cache-${{ env.VERSION }}-arm64
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LIBS }}:cache-${{ env.VERSION }}-arm64,mode=max

  publish-manifest:
    runs-on: ubuntu-24.04
    needs: [build-amd64, build-arm64]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create multi-arch manifest
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LIBS }}
          VERSION=${{ env.VERSION }}
          docker buildx imagetools create \
            --tag ${IMAGE}:${VERSION} \
            --tag ${IMAGE}:latest \
            ${IMAGE}:${VERSION}-amd64 \
            ${IMAGE}:${VERSION}-arm64
