name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  build_libs:
    runs-on: Pyinstaller-runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        uname -a
        ldd --version
        sudo add-apt-repository ppa:longsleep/golang-backports
        sudo apt-get update
        sudo apt-get install -y golang-1.22
        ls -l /usr/bin/go
        ls -l /usr/lib/go-1.22/bin
        sudo rm /usr/bin/go
        sudo ln -s /usr/lib/go-1.22/bin/go /usr/bin/go
        ls -l /usr/bin/go
        go version
        go env
        sudo apt-get install -y protobuf-compiler protobuf-compiler-grpc

    - name: GO setup
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Get Aikido version
      run: |
        AIKIDO_VERSION=$(grep '# define PHP_AIKIDO_VERSION' include/php_aikido.h | awk -F'"' '{print $2}')
        echo $AIKIDO_VERSION
        echo "AIKIDO_VERSION=$AIKIDO_VERSION" >> $GITHUB_ENV

    - name: Build Aikido Agent
      run: |
        cd lib
        protoc --go_out=agent --go-grpc_out=agent ipc.proto
        cd agent
        go get main/ipc/protos
        go get google.golang.org/grpc
        go build -buildmode=c-shared -o ../../build/aikido_agent.so
        ls -l ../../build
        nm -D ../../build/aikido_agent.so
        ldd ../../build/aikido_agent.so

    - name: Build Aikido Request Processor
      run: |
        pwd
        ls -l ${{ github.workspace }}/build/
        cd lib
        protoc --go_out=request-processor --go-grpc_out=request-processor ipc.proto
        cd request-processor
        go get main/ipc/protos
        go get google.golang.org/grpc
        go build -buildmode=c-shared -o ../../build/aikido_request_processor.so
        ls -l ../../build
        nm -D ../../build/aikido_request_processor.so
        ldd ../../build/aikido_request_processor.so

    - name: Archive agent 
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: aikido_agent
        path: ${{ github.workspace }}/build/aikido_agent.so

    - name: Archive request processor
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: aikido_request_processor
        path: ${{ github.workspace }}/build/aikido_request_processor.so

  build_php_extension:
    runs-on: Pyinstaller-runner
    strategy:
      matrix:
        php_version: ['8.4']
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf bison re2c libxml2-dev libssl-dev libcurl4-gnutls-dev
        ldd --version
        sudo apt-get install php${{ matrix.php_version }}-devel

    - name: Get Aikido version
      run: |
        AIKIDO_VERSION=$(grep '# define PHP_AIKIDO_VERSION' include/php_aikido.h | awk -F'"' '{print $2}')
        echo $AIKIDO_VERSION
        echo "AIKIDO_VERSION=$AIKIDO_VERSION" >> $GITHUB_ENV
        echo "AIKIDO_ARTIFACT=aikido-$AIKIDO_VERSION-extension-php-${{ matrix.php_version }}" >> $GITHUB_ENV

    - name: Check PHP setup
      run: |
        which php
        php -v
        php -i

    - name: Build extension
      run: |
        cd ${{ github.workspace }}
        rm -rf build
        mkdir build
        cd lib/php-extension
        phpize
        cd ../../build
        CXX=g++ CXXFLAGS="-fPIC -g -O0 -I../include" LDFLAGS="-lstdc++" ../lib/php-extension/configure
        make
        sudo make install

    - name: Run tests
      run: |
        cd ${{ github.workspace }}
        export TEST_PHP_EXECUTABLE=/usr/bin/php
        /usr/bin/php libphp-extension/run-tests.php ./tests
      continue-on-error: true

    - name: Version Aikido extension
      run: |
        cd ${{ github.workspace }}/build/modules
        mv aikido.so ${{ env.AIKIDO_ARTIFACT }}.so
        
    - name: Archive build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.AIKIDO_ARTIFACT }}
        path: ${{ github.workspace }}/build/modules/${{ env.AIKIDO_ARTIFACT }}.so

  build_rpm_package:
    runs-on: ubuntu-latest
    container:
      image: centos:latest
    needs: [ build_libs, build_php_extension ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rpmdevtools
        run: |
          cd /etc/yum.repos.d/
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
          yum -y install epel-release
          yum -y install rpmdevtools

      - name: Get Aikido version
        run: |
          AIKIDO_VERSION=$(grep '# define PHP_AIKIDO_VERSION' include/php_aikido.h | awk -F'"' '{print $2}')
          echo $AIKIDO_VERSION
          echo "AIKIDO_VERSION=$AIKIDO_VERSION" >> $GITHUB_ENV
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: |
            aikido-${{ env.AIKIDO_VERSION }}*

      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: aikido_agent

      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: aikido_request_processor

      - name: List Artifacts
        run: |
          ls -l -R | grep aikido
          pwd
      
      - name: Prepare rpm package
        run: |
          mv aikido_agent/aikido_agent.so package/rpm/opt/aikido/aikido_agent.so
          mv aikido_request_processor/aikido_request_processor.so package/rpm/opt/aikido/aikido_request_processor.so
          mv aikido-${{ env.AIKIDO_VERSION }}*/build/modules/aikido-${{ env.AIKIDO_VERSION }}* package/rpm/opt/aikido/
          chmod 777 package/rpm/opt/aikido/*
          rpmdev-setuptree
          mkdir -p ~/rpmbuild/SOURCES/aikido-php-firewall-${{ env.AIKIDO_VERSION }}
          cp -rf package/rpm/opt ~/rpmbuild/SOURCES/aikido-php-firewall-${{ env.AIKIDO_VERSION }}/
          cp -f package/rpm/aikido.spec ~/rpmbuild/SPECS/

      - name: Setup RPM for prod
        run: |
          echo "AIKIDO_ARTIFACT=aikido-php-firewall-$AIKIDO_VERSION-1.x86_64.rpm" >> $GITHUB_ENV
          rm -f ~/rpmbuild/SOURCES/aikido-php-firewall-${{ env.AIKIDO_VERSION }}/opt/aikido/aikido-dev.ini
          rm -f ~/rpmbuild/SOURCES/aikido-php-firewall-${{ env.AIKIDO_VERSION }}/opt/aikido/config-dev.json
          sed -i "s/aikido-dev.ini/aikido.ini/" ~/rpmbuild/SPECS/aikido.spec

      - name: Build rpm package
        run: |
          cd ~/rpmbuild/SOURCES
          tar czvf ~/rpmbuild/SOURCES/aikido-php-firewall-${{ env.AIKIDO_VERSION }}.tar.gz *
          rm -rf ~/rpmbuild/SOURCES/aikido-php-firewall-${{ env.AIKIDO_VERSION }}
          rpmbuild --define "debug_package %{nil}" -ba ~/rpmbuild/SPECS/aikido.spec
      
      - name: Archive rpm package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.AIKIDO_ARTIFACT }}
          if-no-files-found: error
          path: |
            ~/rpmbuild/RPMS/x86_64/${{ env.AIKIDO_ARTIFACT }}