# syntax=docker/dockerfile:1.7
# CentOS Stream 9 test image with PHP (from Remi) preinstalled per version,
# plus httpd (mod_php), nginx + php-fpm, MySQL server and Python deps.

ARG BASE_IMAGE=quay.io/centos/centos:stream9
ARG PHP_VERSION=8.3

FROM ${BASE_IMAGE}
SHELL ["/bin/bash", "-euo", "pipefail", "-c"]


# Remi repo + chosen PHP stream
ARG PHP_VERSION
RUN yum install -y yum-utils
RUN dnf -y install https://rpms.remirepo.net/enterprise/remi-release-9.rpm 
RUN yum install -y gcc 
RUN yum install -y python3-devel
RUN dnf --assumeyes module reset php
RUN dnf --assumeyes --nogpgcheck module install php:remi-${PHP_VERSION}
RUN dnf --assumeyes install php-pdo
RUN dnf --assumeyes install php-mysqlnd
RUN yum install -y mod_php nginx php-fpm procps-ng mysql-server


# Python deps used by your test harness
RUN python3 -m pip install --no-cache-dir --upgrade pip \
 && python3 -m pip install --no-cache-dir flask requests psutil

 RUN yum install -y httpd
# Quality-of-life
ENV TZ=Etc/UTC
WORKDIR /work
CMD ["bash"]
