name: Tester Action

on:
  push:
    branches:
      - add-tester-action
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-php:
    name: PHP Tests (zen-demo-php)
    runs-on: ubuntu-latest
    steps:

      - name: Checkout demo app
        uses: actions/checkout@v4
        with:
          repository: Aikido-demo-apps/zen-demo-php
          path: ./zen-demo
          ref: dynamic-firewall-version
          submodules: recursive

      - name: Test Local Action
        id: test-action
        uses: AikidoSec/firewall-tester-action@releases/v1
        with:
          dockerfile_path: ./zen-demo/Dockerfile
          sleep_before_test: 20
          skip_tests: test_api_spec
          extra_build_args: "--build-arg PHP_FIREWALL_VERSION=1.0.125"
          
     